### ISSUE TITLE
Make it so you can enter a blank string for careers and address

### ISSUE THREAD

**Issue by logmannn** [codementorship/austin-tech-list#32]
Currently a website like https://www.auntbertha.com/ doesn't have a careers section so it will fail the build if you enter a blank string. Also some places are only remote

**Comment by somewhatabstract** [comment]
#30 makes it so that Address can be `Remote`. What do you think about leaving it like that since it makes it clear that the job is a remote-only hirer?

Doesn't address the careers part of this issue, though.

**Comment by handeyeco** [comment]
Careers is allowed to be an empty string: `expect(entry.careers === '' || regex.test(entry.careers))`. I need to write more docs, I didn't realize people would actually be interested in this. 🙌

**Comment by somewhatabstract** [comment]
From acorns mighty oak trees grow!

**Comment by handeyeco** [comment]
Closing because I think we addressed the ticket.
