### ISSUE TITLE
Add a github.io site to show the jobs list

### ISSUE THREAD

**Issue by somewhatabstract** [codementorship/austin-tech-list#39]
Currently, we have a demo page that lists the jobs.

What about extending this to be a github.io hosted page that we can link to with a little extra polish?

**Comment by handeyeco** [comment]
Absolutely! In the long run, I think it'd be fun to build out a React project that uses Google Maps/Mapbox/something to map out the locations. I think that would be another repo though that imports the list via npm.

In the meantime I agree it would be neat to host the demo list on Github pages. I think I originally `demo.html` was named `index.html` but then I changed it and Github pages needs it to be `index.html`.

**Comment by handeyeco** [comment]
Done with #43
